apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/api

patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
- path: ingress-patch.yaml
images:
- name: demo-api
  newName: demo-api
  newTag: "3"
